title: John Watrous
description: John Watrous's web page
baseurl: ""
url: "https://jhwatrous.github.io"

markdown: kramdown
highlighter: rouge
theme: minima
collections:
  pdfs:
    output: true
    permalink: /:name/